src/main/java/uteplitel36/domain/Category.java
package uteplitel36.domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Category {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    private String name;

    private String description;

    private String description_h;

    private String keyword;

    private String title;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription_h() {
        return description_h;
    }

    public void setDescription_h(String description_h) {
        this.description_h = description_h;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getKeyword() {
        return keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }
}

src/main/java/uteplitel36/domain/Item.java
package uteplitel36.domain;

import javax.persistence.*;

@Entity
public class Item {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    private String code;
    private String name;
    private String brand;
    private String category;

    @Column(name = "sub_category")
    private String subCategory;

    private Float price;
    private String image;
    private String description;
    private String model;
    private String measure;
    private Float square;
    private Float capacity;
    private String application;
    private String keyWord;
    private Boolean inStock;
    private Long count;
    private String title;
    private String h_description;

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "h_description")
    public String getH_description() {
        return h_description;
    }

    public void setH_description(String h_description) {
        this.h_description = h_description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "key_word", nullable = false)
    public String getKeyWord() {
        return keyWord;
    }

    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getSubCategory() {
        return subCategory;
    }

    public void setSubCategory(String subCategory) {
        this.subCategory = subCategory;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public Float getPrice() {

        return price;
    }

    public void setPrice(Float cost) {
        this.price = cost;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public String getMeasure() {
        return measure;
    }

    public void setMeasure(String measure) {
        this.measure = measure;
    }

    public Float getSquare() {
        return square;
    }

    public void setSquare(Float square) {
        this.square = square;
    }

    public Float getCapacity() {
        return capacity;
    }

    public void setCapacity(Float capacity) {
        this.capacity = capacity;
    }

    public String getApplication() {
        return application;
    }

    public void setApplication(String application) {
        this.application = application;
    }

    @Column(name = "in_stock", nullable = false)
    public Boolean getInStock() {
        return inStock;
    }

    public void setInStock(Boolean inStock) {
        this.inStock = inStock;
    }

    public Long getCount() {
        return count;
    }

    public void setCount(Long count) {
        this.count = count;
    }
}

src/main/java/uteplitel36/domain/SubCategory.java
package uteplitel36.domain;

import javax.persistence.*;

@Entity
@Table(name = "sub_category")
public class SubCategory {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    private String name;

    private String description;

    private String keyword;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getKeyword() {
        return keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }
}

src/main/java/uteplitel36/model/CartInfo.java
package uteplitel36.model;

import java.util.ArrayList;
import java.util.List;

public class CartInfo {

    private int orderNum;

    private CustomerInfo customerInfo;

    private final List<CartLineInfo> cartLines = new ArrayList<CartLineInfo>();

    public CartInfo() {

    }


    public int getOrderNum() {
        return orderNum;
    }

    public void setOrderNum(int orderNum) {
        this.orderNum = orderNum;
    }

    public CustomerInfo getCustomerInfo() {
        return customerInfo;
    }

    public void setCustomerInfo(CustomerInfo customerInfo) {
        this.customerInfo = customerInfo;
    }

    public List<CartLineInfo> getCartLines() {
        return this.cartLines;
    }

    private CartLineInfo findLineByCode(String code) {
        for (CartLineInfo line : this.cartLines) {
            if (line.getProductInfo().getCode().equals(code)) {
                return line;
            }
        }
        return null;
    }

    public void addProduct(ProductInfo productInfo, int quantity) {
        CartLineInfo line = this.findLineByCode(productInfo.getCode());

        if (line == null) {
            line = new CartLineInfo();
            line.setQuantity(0);
            line.setProductInfo(productInfo);
            this.cartLines.add(line);
        }
        int newQuantity = line.getQuantity() + quantity;
        if (newQuantity <= 0) {
            this.cartLines.remove(line);
        } else {
            line.setQuantity(newQuantity);
        }
    }

    public void validate() {

    }

    public void updateProduct(String code, int quantity) {
        CartLineInfo line = this.findLineByCode(code);

        if (line != null) {
            if (quantity <= 0) {
                this.cartLines.remove(line);
            } else {
                line.setQuantity(quantity);
            }
        }
    }

    public void removeProduct(ProductInfo productInfo) {
        CartLineInfo line = this.findLineByCode(productInfo.getCode());
        if (line != null) {
            this.cartLines.remove(line);
        }
    }

    public boolean isEmpty() {
        return this.cartLines.isEmpty();
    }

    public boolean isValidCustomer() {
        return this.customerInfo != null && this.customerInfo.isValid();
    }

    public int getQuantityTotal() {
        int quantity = 0;
        for (CartLineInfo line : this.cartLines) {
            quantity += line.getQuantity();
        }
        return quantity;
    }

    public double getAmountTotal() {
        double total = 0;
        for (CartLineInfo line : this.cartLines) {
            total += line.getAmount();
        }
        return total;
    }

    public void updateQuantity(CartInfo cartForm) {
        if (cartForm != null) {
            List<CartLineInfo> lines = cartForm.getCartLines();
            for (CartLineInfo line : lines) {
                this.updateProduct(line.getProductInfo().getCode(), line.getQuantity());
            }
        }

    }

}

src/main/java/uteplitel36/model/CartLineInfo.java
package uteplitel36.model;

public class CartLineInfo {

    private ProductInfo productInfo;
    private int quantity;

    public CartLineInfo() {
        this.quantity = 0;
    }

    public ProductInfo getProductInfo() {
        return productInfo;
    }

    public void setProductInfo(ProductInfo productInfo) {
        this.productInfo = productInfo;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

//    public boolean isFloatA(){
//        return (this.productInfo.getPrice() * this.quantity) % 1 != 0;
//    }
//
//    public boolean isFloat(){
//        return this.productInfo.getPrice() % 1 != 0;
//    }

    public double getAmount() {
        return this.productInfo.getPrice() * this.quantity;
    }

//    public String getAmountF() {
//        String[] s = String.valueOf(this.productInfo.getPrice() * this.quantity).split(",");
//        return s[0]+"."+s[1]+"0р.";
//    }
}

src/main/java/uteplitel36/controller/OrderController.java
package uteplitel36.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.ui.Model;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.support.ByteArrayMultipartFileEditor;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;
import uteplitel36.dao.OrderDAO;
import uteplitel36.domain.User;
import uteplitel36.model.CartInfo;
import uteplitel36.model.OrderDetailInfo;
import uteplitel36.model.OrderInfo;
import uteplitel36.model.ProductInfo;
import uteplitel36.repos.UserRepo;
import uteplitel36.util.Utils;
import uteplitel36.validator.ProductInfoValidator;

import javax.servlet.http.HttpServletRequest;
import java.util.List;

@Controller
@Transactional
@EnableWebMvc
public class OrderController {

    private final OrderDAO orderDAO;
    private final UserRepo userRepo;
    private final ProductInfoValidator productInfoValidator;

    @Autowired
    public OrderController(OrderDAO orderDAO, UserRepo userRepo, ProductInfoValidator productInfoValidator) {
        this.orderDAO = orderDAO;
        this.userRepo = userRepo;
        this.productInfoValidator = productInfoValidator;
    }

    @InitBinder
    public void myInitBinder(WebDataBinder dataBinder) {
        Object target = dataBinder.getTarget();
        if (target == null) {
            return;
        }

        if (target.getClass() == ProductInfo.class) {
            dataBinder.setValidator(productInfoValidator);
            // For upload Image.
            dataBinder.registerCustomEditor(byte[].class, new ByteArrayMultipartFileEditor());
        }
    }

    @RequestMapping(value = { "/login" }, method = RequestMethod.GET)
    public String login(
            HttpServletRequest request,
            Model model) {
        CartInfo myCart = Utils.getCartInSession(request);

        model.addAttribute("cartSize", myCart.getCartLines().size());
        return "login";
    }

    @PreAuthorize("hasAuthority('ADMIN') or hasAuthority('EMPLOYEE')")
    @RequestMapping(value = { "/orderList" }, method = RequestMethod.GET)
    public String orderList(
            HttpServletRequest request,
            Model model,
            Pageable pageable) {
        CartInfo myCart = Utils.getCartInSession(request);

        model.addAttribute("cartSize", myCart.getCartLines().size());
        Page<OrderInfo> paginationResult = orderDAO.listOrderInfo(pageable);

        model.addAttribute("paginationResult", paginationResult);
        model.addAttribute("totalRecords", paginationResult.getContent().size());
        model.addAttribute("url", "/orderList");
        return "orderList";
    }

    @RequestMapping(value = { "/orderList/{userId}" }, method = RequestMethod.GET)
    public String orderListForUser(
            HttpServletRequest request,
            Model model,
            @PathVariable String userId,
            Pageable pageable) {

        User user = userRepo.findByIdExt(userId);
        Page<OrderInfo> paginationResult = orderDAO.listOrderInfoForUser(pageable, user.getId());

        CartInfo myCart = Utils.getCartInSession(request);
        model.addAttribute("cartSize", myCart.getCartLines().size());
        model.addAttribute("paginationResult", paginationResult);
        model.addAttribute("totalRecords", paginationResult.getContent().size());
        model.addAttribute("url", "/orderList");
        return "orderList";
    }

    @RequestMapping(value = { "/order/{orderId}" }, method = RequestMethod.GET)
    public String orderView(HttpServletRequest request,
                            Model model,
                            @PathVariable String orderId,
                            Pageable pageable) {
        CartInfo myCart = Utils.getCartInSession(request);

        model.addAttribute("cartSize", myCart.getCartLines().size());
        OrderInfo orderInfo = null;
        if (orderId != null) {
            orderInfo = this.orderDAO.getOrderInfo(orderId);
        }
        if (orderInfo == null) {
            return "redirect:/orderList";
        }
        List<OrderDetailInfo> details = this.orderDAO.listOrderDetailInfos(orderId);
        orderInfo.setDetails(details);

        model.addAttribute("orderInfo", orderInfo);

        Page<OrderInfo> paginationResult //
                = orderDAO.listOrderInfo(pageable);

        model.addAttribute("paginationResult", paginationResult);

        return "order";
    }

}

src/main/java/uteplitel36/controller/RegistrationController.java
package uteplitel36.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.util.StringUtils;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import uteplitel36.domain.User;
import uteplitel36.model.CartInfo;
import uteplitel36.service.UserSevice;
import uteplitel36.util.Utils;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import java.util.Map;

@Controller
public class RegistrationController {
    private final UserSevice userSevice;

    @Autowired
    public RegistrationController(UserSevice userSevice) {
        this.userSevice = userSevice;
    }

    @GetMapping("/registration")
    public String registration(HttpServletRequest request,
                               Model model) {
        CartInfo myCart = Utils.getCartInSession(request);

        model.addAttribute("cartSize", myCart.getCartLines().size());
        return "registration";
    }

    @GetMapping("/403")
    public String invalidRoute403() {
        return "error/403";
    }

    @PostMapping("/registration")
    public String addUser(
            HttpServletRequest request,
            @RequestParam("password2") String passwordConfirm,
            @Valid User user,
            BindingResult bindingResult,
            Model model
    ) {
        CartInfo myCart = Utils.getCartInSession(request);

        model.addAttribute("cartSize", myCart.getCartLines().size());
        boolean isConfirmEmpty = StringUtils.isEmpty(passwordConfirm);

        if (isConfirmEmpty) {
            model.addAttribute("password2Error", "Подтверждение пароля не может быть пустым");
        }

        boolean isConfirmPassword = true;
        if (user.getPassword() != null && !user.getPassword().equals(passwordConfirm)) {
            model.addAttribute("passwordError", "Пароли разные!");
            isConfirmPassword = false;
        }

        boolean isPasswordNormLeng = true;
        if (user.getPassword() != null && user.getPassword().length() < 4) {
            model.addAttribute("passwordError", "Пароль не может быть меньше 4 символов!");
            isPasswordNormLeng = false;
        }

        if (isConfirmEmpty || !isConfirmPassword || !isPasswordNormLeng || bindingResult.hasErrors()) {
            Map<String, String> errors = ControllerUtils.getErrors(bindingResult);

            model.mergeAttributes(errors);

            return "registration";
        }

        if (!userSevice.addUser(user)) {
            model.addAttribute("emailError", "Пользователь с таким E-Mail уже существует!");
            return "registration";
        }

        return "redirect:/login";
    }
}

src/main/resources/templates/login.ftl
<#import "parts/common.ftl" as c>
<#include "parts/security.ftl">
<#import "parts/login.ftl" as l>

<@c.page >
    <div class="tab-content col-sm-12">
        <div class="iq-card">
            <div class="iq-card-body">
                <div class="sign-in-from">
                    <h1 class="mb-0">Вход</h1>
                    <#if Session?? && Session.SPRING_SECURITY_LAST_EXCEPTION??>
                        <div class="alert alert-danger" role="alert">
                            ${"Ошибка: Неправильный E-Mail и/или пароль!"}
                        </div>
                    </#if>
                    <#if message??>
                        <div class="alert alert-${messageType}" role="alert">
                            ${message}
                        </div>
                    </#if>
                    <@l.login "/login" false/>
                </div>
            </div>
        </div>
    </div>
</@c.page>

src/main/resources/templates/orderList.ftl
<#import "parts/common.ftl" as c>
<#import "parts/pager.ftl" as p>
<#include "parts/security.ftl">

<@c.page >
    <div class="col-sm-12">
        <div class="tab-content">
            <div class="iq-card">
                <div class="iq-card-body">
                    <h2>Список заказов</h2>
                    <p>Общее количество заказов: ${totalRecords}</p>
                </div>
            </div>
        </div>
    </div>

    <@p.pager paginationResult url />
    <div class="col-sm-12">
        <div class="iq-card">
            <div class="iq-card-body">
                <div class="table-responsive">
                    <table class="files-lists table table-striped mt-4">
                        <thead>
                        <tr>
                            <#if isAdmin>
                                <th scope="col">Номер заказа</th>
                            </#if>
                            <th scope="col">Дата заказа</th>
                            <th scope="col">Имя заказчика</th>
                            <th scope="col">Фамилия заказчика</th>
                            <th scope="col">Адрес заказчика</th>
                            <th scope="col">E-Mail заказчика</th>
                            <th scope="col">Стоимость заказа</th>
                            <th scope="col">Подробнее</th>
                        </tr>
                        </thead>
                        <tbody>
                        <#list paginationResult.content as orderInfo>
                            <tr>
                                <#if isAdmin>
                                    <td>${orderInfo.orderNum}</td>
                                </#if>
                                <td>${orderInfo.orderDate}
                                </td>
                                <td>${orderInfo.customerFirstname}</td>
                                <td>${orderInfo.customerSecondame}</td>
                                <td>${orderInfo.customerAddress}</td>
                                <td>${orderInfo.customerEmail}</td>
                                <td style="color:red;">
                                    ${orderInfo.amount}p.
                                </td>
                                <td><a href="/order/${orderInfo.id}">
                                        Подробнее</a></td>
                            </tr>
                        </#list>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <@p.pager paginationResult url />
</@c.page>

src/main/resources/templates/payment.ftl
<#import "parts/common.ftl" as c>

<@c.page>
    <div class="col-md-10 offset-md-1">
        <div class="tab-content">
            <div class="iq-card">
                <div class="iq-card-body">
                    <h4 class="mt-2"><b>Оплата</b></h4>
                    <p><br>Физическим лицам:<br>
                        Оплата товара производится при получении товара с доставкой курьеру наличными/банковской картой.
                        При самовывозе оплата в кассу наличными/банковской картой.<br><br>
                        Юридическим лицам:<br>
                        Оплата производится через банк, путем выставления счета с НДС.

                        <b>Обьектные скидки</b><br>
                    </p>
                </div>
            </div>
        </div>
    </div>

</@c.page>

src/main/resources/templates/shoppingCartConfirmation.ftl
<#import "parts/common.ftl" as c>
<#include "parts/security.ftl">

<@c.page >
    <div class="col-sm-12">
        <div class="tab-content">
            <div class="iq-card">
                <div class="iq-card-body">
                    <h2>Подтверждение заказа</h2>
                </div>
            </div>
        </div>
    </div>

    <div class="col-sm-12">
        <div class="iq-card">
            <div class="iq-card-body">
                <div class="friend-list-tab mt-2">
                    <div class="tab-content">
                        <div class="tab-pane fade active show" id="all-friends" role="tabpanel">
                            <div class="iq-card-body p-0">
                                <div class="row">
                                    <#list myCart.cartLines as productList>
                                        <div class="col-md-3">
                                            <div class="iq-card">
                                                <div class="iq-card-body profile-page p-0">
                                                    <div class="profile-header-image">
                                                        <div class="cover-container justify-content-center d-flex"
                                                                <#--                                                             style="transform: translate(25%, 0);width: 150px;"-->
                                                        >
                                                            <img src="${productList.productInfo.image}"
                                                                 alt="profile-bg" class="rounded img-fluid w-100">
                                                        </div>
                                                        <div class="profile-info p-4">
                                                            <div class="user-detail">
                                                                <div class="flex-wrap justify-content-between align-items-start">
                                                                    <div class="profile-detail d-flex">
                                                                        <div class="user-data-block">
                                                                            <h4>${productList.productInfo.price}p.</h4>
                                                                            <p style="font-size: 11px">${productList.productInfo.name}</p>

                                                                            <p>Количество: ${productList.quantity}</p>
                                                                            <p>Итоговая цена: ${productList.amount}
                                                                                p.</p>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </#list>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="tab-content col-sm-12">
        <div class="iq-card">
            <div class="iq-card-body">
                <div class="row">
                    <div class="col-md-9 pl-4">
                        <div class="tab-content">
                            <h4>Информация заказчика:</h4>
                            <hr>
                            <div class="row">
                                <div class="col-3">
                                    <h6>Имя:</h6>
                                </div>
                                <div class="col-9">
                                    <#if myCart.customerInfo.firstname??>
                                        <p class="mb-0">${myCart.customerInfo.firstname}</p>
                                    </#if>
                                </div>
                                <div class="col-3">
                                    <h6>Фамилия:</h6>
                                </div>
                                <div class="col-9">
                                    <#if myCart.customerInfo.secondname??>
                                        <p class="mb-0">${myCart.customerInfo.secondname}</p>
                                    </#if>
                                </div>
                                <div class="col-3">
                                    <h6>Email:</h6>
                                </div>
                                <div class="col-9">
                                    <p class="mb-0">${myCart.customerInfo.email}</p>
                                </div>
                                <div class="col-3">
                                    <h6>Телефон:</h6>
                                </div>
                                <div class="col-9">
                                    <#if myCart.customerInfo.phone??>
                                        <p class="mb-0">+7 ${myCart.customerInfo.phone}</p>
                                    </#if>
                                </div>
                                <div class="col-3">
                                    <h6>Адрес:</h6>
                                </div>
                                <div class="col-9">
                                    <p class="mb-0">${myCart.customerInfo.address}</p>
                                </div>
                                <div class="col-3">
                                    <h6>Способ получения:</h6>
                                </div>
                                <div class="col-9">
                                    <p class="mb-0">${myCart.customerInfo.shipping}</p>
                                </div>
                            </div>
                            <h4 class="mt-3">Итог по заказу:</h4>
                            <hr>
                            <div class="row">
                                <div class="col-3">
                                    <h6>Количество:</h6>
                                </div>
                                <div class="col-9">
                                    <p class="mb-0">${myCart.quantityTotal}</p>
                                </div>
                                <div class="col-3">
                                    <h6>Итоговая цена:</h6>
                                </div>
                                <div class="col-9">
                                    <p class="mb-0">${myCart.amountTotal}p.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="tab-content col-sm-12">
        <div class="iq-card">
            <div class="iq-card-body">
                <form class="col-md-12" action="/shoppingCartConfirmation" method="post">
                    <input type="hidden" name="_csrf" value="${_csrf.token}"/>
                    <input type="hidden" name="isUserAuth" <#if user??>value="1"<#else>value="2"</#if>/>
                    <div class="d-inline-block w-100">
                        <div class="row">
                            <div class="col-md-3">
                                <span class="dark-color justify-content-center d-flex line-height-2 mt-2">
                                    <a
                                            type="button"
                                            class="btn btn-primary"
                                            href="/shoppingCart">Изменить корзину
                                    </a>
                                </span>
                            </div>
                            <div class="col-md-4">
                                <span class="dark-color justify-content-center d-flex line-height-2 mt-2">
                                    <a
                                            type="button"
                                            class="btn btn-primary"
                                            href="/shoppingCartCustomer">Изменить информацию покупателя
                                    </a>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="sign-info mt-3 pt-3">
                        <div class="row">
                            <div class="col-md-3 offset-md-9 justify-content-center d-flex">
                                <button type="submit"
                                        style="width: 288px"
                                        class="btn btn-success">Заказать
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</@c.page>